version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.6.4 # every job must define an image for the docker executor and subsequent jobs may define a different image.
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Runing test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            export APP_SETTINGS="config.DevelopmentConfig"
            python -m unittest

workflows:
  main:
    jobs:
      - test
