version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            python3 -m venv venv
            source venv/bin/activate
            python -m unittest
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
  install_dependencies:
    executor: python/default
    steps:
      - run:
          name: "Install Heroku CLI, if necessary"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
  docker-build-release:
    executor: python/default
    parameters:
      app-name:
        description: "The Heroku app name to which the application should be deployed"
        type: string
        default: "floating-ocean-24238"
      app-arg:
        description: "The Heroku Dockerfile args"
        type: string
        default: "none"
      app-type:
        description: "The Heroku app type (web or worker) of the application to be deployed"
        type: string
        default: "web"
    steps:
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Deploy Heroku Docker Container
          command: |
            heroku container:push << parameters.app-type >> -a << parameters.app-name >> --arg << parameters.app-arg >>
            heroku container:release << parameters.app-type >> -a << parameters.app-name >>

workflows:
  main:
    jobs:
      - build-and-test
      - install_dependencies
      - docker-build-release